//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.DISCIPLINES = new HashSet<DISCIPLINES>();
            this.GROUP = new HashSet<GROUP>();
        }
    
        public int DEPARTMENT_ID { get; set; }
        public int FACULTY_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public int TEACHER_ID { get; set; }
        public string DEPARTMENT_OFFICE { get; set; }
        public int DEPARTMENT_BUILDING { get; set; }
        public string DEPARTMENT_PHONE { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual ICollection<DISCIPLINES> DISCIPLINES { get; set; }
        public virtual ICollection<GROUP> GROUP { get; set; }
    }
}
