//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINES
    {
        public DISCIPLINES()
        {
            this.DISCIPLINES_TEACHERS = new HashSet<DISCIPLINES_TEACHERS>();
        }
    
        public int DISCIPLINES_ID { get; set; }
        public int DEPARTMENT_ID { get; set; }
        public string DISCIPLINES_NAME { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<DISCIPLINES_TEACHERS> DISCIPLINES_TEACHERS { get; set; }
    }
}
