//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINES_TEACHERS
    {
        public DISCIPLINES_TEACHERS()
        {
            this.STATEMENT_MARKS = new HashSet<STATEMENT_MARKS>();
            this.STATEMENT_SESSION = new HashSet<STATEMENT_SESSION>();
        }
    
        public int DISCIPLINES_TEACHER_ID { get; set; }
        public int DISCIPLINES_ID { get; set; }
        public int TEACHER_ID { get; set; }
    
        public virtual DISCIPLINES DISCIPLINES { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual ICollection<STATEMENT_MARKS> STATEMENT_MARKS { get; set; }
        public virtual ICollection<STATEMENT_SESSION> STATEMENT_SESSION { get; set; }
    }
}
