//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY
    {
        public FACULTY()
        {
            this.DEPARTMENT = new HashSet<DEPARTMENT>();
        }
    
        public int FACULTY_ID { get; set; }
        public string FACULTY_NAME { get; set; }
        public int TEACHER_ID { get; set; }
        public string FACULTY_OFFICE { get; set; }
        public int FACULTY_BUILDING { get; set; }
        public string FACULTY_PHONE { get; set; }
    
        public virtual ICollection<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
