//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public GROUP()
        {
            this.STUDENTS = new HashSet<STUDENTS>();
        }
    
        public int GROUP_ID { get; set; }
        public int DEPARTMENT_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public int TEACHER_ID { get; set; }
        public int GROUP_YEAR { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual ICollection<STUDENTS> STUDENTS { get; set; }
    }
}
