//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbdeevMarksStudentsEntities : DbContext
    {
        private static AbdeevMarksStudentsEntities _context;

        public static AbdeevMarksStudentsEntities GetContext()
        {
            if( _context == null )
                _context = new AbdeevMarksStudentsEntities();
            return _context;
        }

        public AbdeevMarksStudentsEntities()
            : base("name=AbdeevMarksStudentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public DbSet<DISCIPLINES> DISCIPLINES { get; set; }
        public DbSet<DISCIPLINES_TEACHERS> DISCIPLINES_TEACHERS { get; set; }
        public DbSet<FACULTY> FACULTY { get; set; }
        public DbSet<GROUP> GROUP { get; set; }
        public DbSet<STATEMENT_MARKS> STATEMENT_MARKS { get; set; }
        public DbSet<STATEMENT_SESSION> STATEMENT_SESSION { get; set; }
        public DbSet<STUDENTS> STUDENTS { get; set; }
        public DbSet<TEACHER> TEACHER { get; set; }
    }
}
