//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATEMENT_SESSION
    {
        public int STATEMENT_SESSION_RECORD_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public int DISCIPLINES_TEACHER_ID { get; set; }
        public int STATEMENT_SESSION_SEMESTER { get; set; }
        public string STATEMENT_SESSION_TYPE_TEST { get; set; }
        public int STATEMENT_SESSION_MARK { get; set; }
        public System.DateTime STATEMENT_SESSION_DATE { get; set; }
    
        public virtual DISCIPLINES_TEACHERS DISCIPLINES_TEACHERS { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
    }
}
