//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class STUDENTS
    {
        public STUDENTS()
        {
            this.STATEMENT_MARKS = new HashSet<STATEMENT_MARKS>();
            this.STATEMENT_SESSION = new HashSet<STATEMENT_SESSION>();
        }
    
        public int STUDENT_ID { get; set; }
        public int GROUP_ID { get; set; }
        public string STUDENT_SURNAME { get; set; }
        public string STUDENT_NAME { get; set; }
        public string STUDENT_PATRONYMIC { get; set; }
        public System.DateTime STUDENT_BIRTHDAY { get; set; }
        public string STUDENT_GENDER { get; set; }
        public string STUDENT_ADDRESS { get; set; }
        public string STUDENT_PHONE { get; set; }
        public string STUDENT_PHOTO { get; set; }

        public string STUDENT_PHOTO_IMAGE
        {
            get
            {
                if (STUDENT_PHOTO != null)
                {
                    string str = "/res/" + STUDENT_PHOTO;
                    return str;
                }
                return null;
            }
        }

        public string GROUP_NAME
        {
            get
            {
                return GROUP.GROUP_NAME;
            }
        }

        public string FIO_STUDENT
        {
            get
            {
                string str = STUDENT_SURNAME + " " + STUDENT_NAME;
                if (STUDENT_PATRONYMIC != null)
                {
                    str += " " + STUDENT_PATRONYMIC;
                }
                return str;
            }
        }

        public decimal STUDENT_AVG_SESSION_MARK
        {
            get
            {
                var context = AbdeevMarksStudentsEntities.GetContext();

                var average = context.STATEMENT_SESSION
                    .Where(ss => ss.STUDENT_ID == this.STUDENT_ID)
                    .Average(ss => (decimal?)ss.STATEMENT_SESSION_MARK);

                return Math.Round(average ?? 0, 2);
            }
        }

        public decimal STUDENT_AVG_MARK
        {
            get
            {
                var context = AbdeevMarksStudentsEntities.GetContext();

                var average = context.STATEMENT_MARKS.Where(ss => ss.STUDENT_ID == this.STUDENT_ID).Average(ss => (decimal?)ss.STATEMENT_MARKS_MARK);


                return Math.Round(average ?? 0, 2);

            }
        }


        public virtual GROUP GROUP { get; set; }
        public virtual ICollection<STATEMENT_MARKS> STATEMENT_MARKS { get; set; }
        public virtual ICollection<STATEMENT_SESSION> STATEMENT_SESSION { get; set; }
    }
}
