//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdeevMarksStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        public TEACHER()
        {
            this.DEPARTMENT = new HashSet<DEPARTMENT>();
            this.DISCIPLINES_TEACHERS = new HashSet<DISCIPLINES_TEACHERS>();
            this.FACULTY = new HashSet<FACULTY>();
            this.GROUP = new HashSet<GROUP>();
        }
    
        public int TEACHER_ID { get; set; }
        public string TEACHER_SURNAME { get; set; }
        public string TEACHER_NAME { get; set; }
        public string TEACHER_PATRONYMIC { get; set; }
        public System.DateTime TEACHER_BIRTHDAY { get; set; }
        public string TEACHER_GENDER { get; set; }
        public string TEACHER_ADDRESS { get; set; }
        public string TEACHER_PHONE { get; set; }
    
        public virtual ICollection<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual ICollection<DISCIPLINES_TEACHERS> DISCIPLINES_TEACHERS { get; set; }
        public virtual ICollection<FACULTY> FACULTY { get; set; }
        public virtual ICollection<GROUP> GROUP { get; set; }
    }
}
